- Justfile
- flake.nix
- package.json
- Modify the cargo build to use the same arguments as the trunk build so it reuses the build artifacts.
- Include rsync in nix flakes
- Cleaned up package.json to be private and remove unnecessary arguments
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/109, https://github.com/Granola-Team/mina-block-explorer/issues/111, https://github.com/Granola-Team/mina-block-explorer/issues/112
> Improve developer experience

- flake.nix
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/147
> [NIX] Use toolchain defined in `rust-toolchain.toml` 

- Cargo.lock
- Cargo.toml
- cypress/e2e/search-bar/search-bar-integration.cy.js
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/196
> Update leptos to fix `cargo audit`

- Justfile
- cypress.config.js
- ops/buildkite-pipeline.yaml
Fixes #217 
... does better cleanup of files and resources (processes).
... the "test" target actually runs all tests, as expected.
... enables concurrent testing on CI, which is otherwise broken due to clashing on the Cypress port.
> Improve Justfile

- scripts/wait-on-port.js
> ensure exit code for wait-for-port.js uses exit code of main process

- src/common/table.rs
Fixes:
* https://github.com/Granola-Team/mina-block-explorer/issues/281
> (table) fix labeling when less than 10 row items

- src/account_dialog/dialog.rs
- src/common/spotlight.rs
> Make account dialog spotlight occupy the full width of the available dialog

- src/common/functions.rs
- src/common/spotlight.rs
> make text smaller, and left column less wide, on mobile

- src/addresses/functions.rs
- src/blocks/table_traits.rs
Closes #309 
Also, standardize how pill colors are used:
* Grey: numeric info such as slots and heights
* Blue: counts
* Orange: fees
* Green: balances and transfers
> Make `coinbase` a green "pill" in the blocks tables

- cypress/e2e/table-columns/ordered-columns.cy.js
- src/blocks/functions.rs
- src/blocks/table_traits.rs
> Remove `height` column on SNARK Jobs tab at the block spotlight level.

- Justfile
- flake.lock
- flake.nix
- ops/buildkite-pipeline.yaml
- pnpm-lock.yaml
Fixes #382 
I updated the CI machines that run the builds. It turns out that we were pretty lucky with the prior setup, in that it did build. New machines were failing. This corrects it, mainly by the "agents: xwindows: true" part of the CI pipeline definition.
> Update CI build definition

- src/blocks/page.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/534
* Only return 1 block in the block spotlight query
> Fix issue where loading an individual block was too slow with the indexer

- src/common/table.rs
Closes #590 
This has the downside of "jumping" columns when the table data is loading since the columns are in "auto" layout mode, but the table is not usable on mobile otherwise.
> Remove table-fixed from <table/> to avoid squishing on mobile

- graphql/queries/account_dialog.graphql
- graphql/queries/snarks.graphql
- src/snarks/graphql.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/601
* Remove workId reference from the codebase
> remove workIds vestiges from the GraphQL queries

- build.rs
- src/common/constants.rs
- src/summary/functions.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/597
To change the GraphQL and REST URLs export the following variables
```
export GRAPHQL_URL=http://localhost:8080/graphql
export REST_URL=http://localhost:8080
nix develop --command just dev
```
> Make GraphQL and REST endpoints configurable by env vars

- src/summary/models.rs
Also changes `u16`/`u64` -> `u32` to [match Indexer](https://github.com/Granola-Team/mina-indexer/blob/7865e798158f5bbb96c8a4cc30c250ce42ebf066/rust/src/web/rest/blockchain.rs#L21).
Resolves Granola-Team/mina-block-explorer#634
Unblocks #629
> Update summary model with staking ledger hash for page header

- ops/buildkite-pipeline.yaml
Without this, every commit is pushed to prod.
> Add check for main branch

- Justfile
Relates to Granola-Team/mina-block-explorer#44 and Granola-Team/mina-block-explorer#700
Our Cloudflare Pages production deployment needs `--branch main`, but it doesn't matter the git branch you are on.
> fix(CD): actually deploy to Prod

- src/accounts/page.rs
> Show standard "no data for this view" when `accounts` is null

- src/common/functions.rs
> Fix verbose SI unit representation in age column

- src/account_activity/components.rs
- src/accounts/page.rs
- src/common/table.rs
Prevents crashing.
Closes #980
> Disable all filter inputs on the account spotlight page

- cypress/e2e/analytics/filter.cy.js
- src/analytics/components.rs
- src/analytics/page.rs
- src/common/components.rs
- src/common/constants.rs
- src/scripts/analytics/avg-snark-fee-per-block.js
Relates to (but does not close): https://github.com/Granola-Team/mina-indexer/issues/1506
We need to remove filtering embedded in graphs and create a URL connected component that support filtering over the entire page. URL connected inputs within this new component is a step towards that end.
> Add chart filters component to support filtering by various data points

- cypress/e2e/tab-number-bubble/tabs.cy.js
- src/account_activity/components.rs
- src/account_activity/models.rs
- src/account_activity/page.rs
Back navigation was being hampered due to panics within the WASM runtime. This is a fix.
#1027
> Fix runtime panics in WASM bundle triggered from the account activity page

- Justfile
Environment variables such as the GRAPHQL_URL and REST_URL are integrated into the source code at compile time. It is easy to publish a bundle to prod without first cleaning `just clean` and changing your environment before rebuilding and publishing `just publish`. This introduces a quick environment variable check just before the `clean` phase in the `publish` step to ensure anything with either `localhost` or `127.0.0.1` are not present in those two variables.
#1033
> Prevent accidentally publishing an incorrectly compiled WASM bundle

- src/common/functions.rs
Only fees should ever be 0.
Fixes Granola-Team/mina-block-explorer#1118
> chore: 0 -> "Free"

- src/analytics/components.rs
Put default values into the control.
Example:
> feat(analytics): set default `Start Block Height` and `End Block Height`
