- LICENSE
- README.md
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/2
> Improve readme

- .github/workflows/node.js.yml
> Issue-45836712 Add workflow to support CI 

- .github/workflows/rust.yml
- app/src/api_models.rs
- app/src/main.rs
- app/src/root.rs
- app/src/summary.rs
- app/src/summary_page.rs
> (leptos-reset) Add github action to run tests in CI

- README.md
closes #27
Added buildkite badge to README.md
No
> add buildkite badge to README.md

- app/src/latest_block_page.rs
- app/src/main.rs
- app/src/nav.rs
- app/src/root.rs
- app/src/table.rs
- app/src/transactions_page.rs
> Transactions Page: HTML structure and data only

- app/src/account_page.rs
- app/src/api_models.rs
- app/src/latest_block_page.rs
- app/src/snarks_page.rs
- app/src/summary_page.rs
- app/src/transactions_page.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/40
> Modify struct attributes to be snake_case

- Cargo.lock
- Cargo.toml
- Justfile
- src/main.rs
- src/nav.rs
- src/root.rs
- src/stakes_page.rs
Can't call the minaexplorer endpoint from [minaexplorer.com/staking](https://minaexplorer.com/staking) due to CORS issue so we're stubbing the request instead
> Add fake Stakes page

- Trunk.toml
- index.html
- src/header.rs
- src/nav.rs
- src/root.rs
- src/table.rs
> desktop layout complete

- ops/buildkite-pipeline.yaml
- src/api_models.rs
- src/nav.rs
- src/summary_item.rs
- src/summary_page.rs
> add styling (minus theme + logo) for summary items

- .vscode/settings.json
- src/latest_block_page.rs
- src/table.rs
> Optional pagination controls added to table. 

- .env.example
- .gitignore
- Justfile
- flake.nix
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/80
> Add dotenv support to Justfile

- .gitignore
- cypress/e2e/account-dialog/dialog-contents.cy.js
- cypress/e2e/navigation/to-snarks.cy.js
- cypress/e2e/navigation/to-transactions.cy.js
- cypress/e2e/spotlight/account-spotlight.cy.js
- cypress/e2e/spotlight/block-spotlight.cy.js
- cypress/e2e/spotlight/transaction-spotlight.cy.js
- cypress/support/commands.js
- graphql/queries/transactions.graphql
- src/accounts/components.rs
- src/accounts/page.rs
- src/blocks/page.rs
- src/common/functions.rs
- src/common/spotlight.rs
- src/root.rs
- src/transactions/components.rs
- src/transactions/functions.rs
- src/transactions/mod.rs
- src/transactions/page.rs
- src/transactions/table_trait.rs
> Add Transaction Spotlight 

- src/header/navigation.rs
> make home icon clickable

- Cargo.lock
- Cargo.toml
- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/support/commands.js
- src/blocks/components.rs
- src/common/search.rs
- src/root.rs
> Add search bar to home page

- Cargo.lock
- Cargo.toml
- Justfile
- cypress/e2e/navigation/mobile-navigation.cy.js
- cypress/e2e/navigation/to-account-spotlight.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/navigation/to-block-spotlight.cy.js
- cypress/e2e/navigation/to-blocks.cy.js
- cypress/e2e/navigation/to-snarks.cy.js
- cypress/e2e/navigation/to-transactions.cy.js
> Improve CI cypress reporting legibility

- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/support/commands.js
- src/snarks/page.rs
> Add search bar to SNARKs page

- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/navigation/to-transactions.cy.js
- src/blocks/table_traits.rs
- src/snarks/page.rs
> Improvements on User Commands table: links & pills

- cypress/e2e/account-dialog/dialog-contents.cy.js
- cypress/e2e/account-dialog/on-pages.cy.js
- cypress/e2e/all/account-page.cy.js
- cypress/e2e/all/footer.cy.js
- cypress/e2e/blocks/blocks-table.cy.js
- cypress/e2e/navigation/desktop-menu-look-and-feel.cy.js
- cypress/e2e/navigation/mobile-menu-look-and-feel.cy.js
- cypress/e2e/navigation/mobile-navigation.cy.js
- cypress/e2e/navigation/to-account-spotlight.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/navigation/to-block-spotlight.cy.js
- cypress/e2e/navigation/to-blocks.cy.js
- cypress/e2e/navigation/to-broadcast.cy.js
- cypress/e2e/navigation/to-snarks.cy.js
- cypress/e2e/navigation/to-transactions.cy.js
- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/e2e/spotlight/account-spotlight.cy.js
- cypress/e2e/spotlight/block-spotlight.cy.js
- cypress/e2e/spotlight/transaction-spotlight.cy.js
- cypress/e2e/stakes/staking-page.cy.js
- cypress/support/e2e.js
- ops/buildkite-pipeline.yaml
> Add tagging for integration tests, and exclude useful, but flakey tests from CI

- LICENSE
- README.md
Fixes granola-team/mina-block-explorer#232
> Fix: add missing MPL-2.0 license file

- src/common/models.rs
- src/summary/models.rs
> #[cfg(test)] for test modules

- .gitignore
- Justfile
- README.md
- flake.nix
- scripts/wait-on-port.js
> Manage background processes for Justfile in node script

- src/common/functions.rs
> fix panic by handling zero-length case

- src/root.rs
> Add NullView to make nested subroutes work

- cypress/e2e/pagination/all.cy.js
- src/blocks/components.rs
- src/common/functions.rs
- src/common/models.rs
- src/common/table.rs
> Make numbers in table pagination clickable

- .vscode/settings.json
> Integrate RUSTFLAGS into VS Code

- graphql/queries/transactions.graphql
- src/common/functions.rs
- src/transactions/functions.rs
- src/transactions/table_trait.rs
- tailwind.config.js
> Add height column with status bubble indicating applied/failed transaction

- Justfile
> Recursively remove all files in bucket before publishing

- graphql/queries/blocks.graphql
- src/addresses/page.rs
- src/blocks/functions.rs
- src/blocks/graphql.rs
- src/blocks/page.rs
- src/blocks/table_traits.rs
- src/broadcast/page.rs
- src/common/components.rs
- src/common/models.rs
- src/header/navigation.rs
> Support "count bubble" in tabs to indicate presence of data

- cypress/e2e/navigation/mobile-navigation.cy.js
- src/common/components.rs
- src/header/navigation.rs
- src/root.rs
- src/transactions/page.rs
> Refactor Transactions page/navigation to support token and zkApp transactions 

- LICENSE
- README.md
Fixes #283.
**Do not squash.**
> Use Apache 2.0 license instead of MPLv2

- Cargo.lock
- Cargo.toml
- flake.lock
- rust-toolchain.toml
- src/addresses/page.rs
- src/common/functions.rs
- src/footer/ga_opt_out.rs
> update leptos to 0.6.9

- cypress/e2e/blocks/blocks-table.cy.js
- cypress/support/commands.js
- src/blocks/table_traits.rs
> move state hash and slot leftwards in all block tables

- src/common/components.rs
> get untracked signals where reactivity is not intended

- src/blocks/components.rs
> remove <Suspense/> component as `fallback` view was being triggered on every resource change

- src/common/table.rs
- tailwind.config.js
> use monospace font in table and remove table: fixed; layout

- cypress/e2e/table-columns/ordered-columns.cy.js
- src/transactions/table_trait.rs
> Add "type" column to transactions table

- cypress/e2e/search-bar/search-bar-integration.cy.js
- src/common/functions.rs
> Make first and last part of hashes in tables visible

- src/common/spotlight.rs
> use monospace fonts for spotlight tables

- cypress/e2e/table-columns/ordered-columns.cy.js
- src/snarks/table_trait.rs
- src/transactions/table_trait.rs
> move state hash leftwards in remaining tables

- Justfile
> remove duplicate 'cargo clippy' command

- src/account_dialog/dialog.rs
- src/common/spotlight.rs
- src/icons/mod.rs
> Create new close icon and adjust positioning within spotlight dialog

- src/common/components.rs
> disable scrolling when clicking 'Include Non-Canonical'

- src/common/components.rs
- src/header/navigation.rs
> Fix navigation menu for tablets

- src/account_dialog/components.rs
- src/blocks/components.rs
- src/common/functions.rs
- src/snarks/components.rs
- src/transactions/components.rs
> Improvements to the quality of the presentation in the subtables for the account dialog

- src/account_dialog/dialog.rs
> restore close button

- src/account_dialog/graphql.rs
- src/blocks/graphql.rs
- src/fee_transfers/graphql.rs
- src/next_stakes/graphql.rs
- src/snarks/graphql.rs
- src/stakes/graphql.rs
- src/transactions/graphql.rs
> avoid serializaing nulls in graphql requests

- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/support/commands.js
- src/transactions/components.rs
- src/transactions/functions.rs
- src/transactions/page.rs
> Make transactions searchable by state hash, not payment iD

- cypress/e2e/blocks/tabs.cy.js
> randomnly audit blocks to check pagination vs tab counts

- cypress/e2e/canonicity/tables.cy.js
- src/blocks/components.rs
- src/blocks/functions.rs
- src/common/components.rs
- src/common/models.rs
- src/snarks/functions.rs
- src/snarks/page.rs
- src/transactions/components.rs
- src/transactions/functions.rs
> Default to canonical data

- cypress/e2e/canonicity/tables.cy.js
- src/blocks/components.rs
> Connect `Blocks` sub-table in `Account Spotlight` page to `canonical` url param

- cypress/e2e/navigation/to-transactions.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- src/common/components.rs
- src/common/functions.rs
> Make hashes copiable directly from table

- src/addresses/functions.rs
- src/blocks/components.rs
- src/transactions/page.rs
> Make various `Spotlight` hashes linkable, where appropriate

- Justfile
> disable file watching for trunk serve

- src/index.html
> fix broken reference to favicon

- Justfile
> fix broken publish command

- src/index.html
> fix broken reference to manifest file in index.html

- Justfile
- Trunk.toml
> Properly clean up all build artifacts

- Trunk.toml
> watch all files in the src/ dir

- Cargo.lock
- Cargo.toml
- src/account_activity/functions.rs
- src/account_activity/page.rs
- src/account_activity/table_traits.rs
- src/header/navigation.rs
- src/root.rs
> Stub account list page

- src/account_activity/functions.rs
- src/common/functions.rs
- src/header/navigation.rs
- src/root.rs
- src/transactions/page.rs
- src/zk_apps/functions.rs
- src/zk_apps/models.rs
- src/zk_apps/page.rs
- src/zk_apps/table_trait.rs
> Stub ZK App (and Token) Transactions page

- src/account_activity/components.rs
- src/account_activity/dialog.rs
- src/account_activity/page.rs
- src/blocks/components.rs
- src/blocks/page.rs
- src/broadcast/components.rs
- src/broadcast/page.rs
- src/common/components.rs
- src/common/search.rs
- src/common/spotlight.rs
- src/common/table.rs
- src/next_stakes/page.rs
- src/snarks/components.rs
- src/snarks/page.rs
- src/stakes/components.rs
- src/stakes/page.rs
- src/summary/page.rs
- src/tokens/page.rs
- src/transactions/components.rs
- src/transactions/page.rs
- src/zk_apps/page.rs
> Use `#[prop(into)]` for `String` props in `#[components]` 

- cypress/e2e/seo-optimization/titles.cy.js
- src/blocks/components.rs
- src/header/navigation.rs
- src/root.rs
- src/tokens/functions.rs
- src/tokens/models.rs
- src/tokens/table_trait.rs
- src/transactions/page.rs
- src/zk_apps/functions.rs
- src/zk_apps/page.rs
- src/zk_apps/table_trait.rs
> Refactor all instances of `trx` to `txn`

- Cargo.lock
- Cargo.toml
- src/account_activity/page.rs
- src/broadcast/components.rs
- src/broadcast/page.rs
- src/common/components.rs
- src/common/spotlight.rs
- src/header/navigation.rs
- src/root.rs
- src/zk_apps/page.rs
> Stub ZK App / Token account page

- src/common/table.rs
> Tighten column spacing in generic table

- src/common/models.rs
> Fix incorrect pagination counts for zero-records case

- cypress/e2e/stakes/staking-page.cy.js
- cypress/support/commands.js
- src/stakes/functions.rs
> Ensure staking page displays values in MINA

- src/account_activity/components.rs
- src/blocks/components.rs
- src/snarks/page.rs
- src/transactions/components.rs
Closes #425 
Relates to closed issue #411
> Remove `.to_owned()` where `&str` suffices

- Justfile
We have created a new ticket to track this: #435
> Ignore advisory warning for now

- src/account_activity/components.rs
- src/account_activity/dialog.rs
- src/account_activity/page.rs
- src/blocks/components.rs
- src/common/components.rs
- src/common/table.rs
- src/header/navigation.rs
- src/next_stakes/page.rs
- src/root.rs
- src/snarks/components.rs
- src/stakes/page.rs
- src/transactions/components.rs
- src/transactions/page.rs
> refactor `<NullView />` references to `().into_view()`

- src/account_activity/functions.rs
- src/blocks/functions.rs
- src/broadcast/page.rs
- src/common/constants.rs
- src/common/mod.rs
- src/next_stakes/functions.rs
- src/snarks/functions.rs
- src/stakes/functions.rs
- src/transactions/functions.rs
> Use constants for graphql and rest endpoints

- src/stakes/page.rs
> Issue single graphql call after summary data loaded

- cypress/e2e/navigation/to-granola.cy.js
- src/common/search.rs
- src/summary/page.rs
@n1tranquilla I'd like to point to https://granola.team with the "Granola" text (modified here in this PR). Can you help do that? I'm not sure how to use the framework to make that happen.
> Point to Granola from home page

- cypress/e2e/pagination/all.cy.js
- cypress/support/commands.js
- src/account_activity/components.rs
- src/common/table.rs
> Fix pagination of `SNARK job` and `Block Production` subtables in `Account Spotlight` page

- src/blocks/components.rs
- src/blocks/page.rs
- src/common/constants.rs
- src/next_stakes/page.rs
- src/snarks/functions.rs
- src/snarks/page.rs
- src/stakes/page.rs
- src/transactions/components.rs
- src/transactions/functions.rs
> Load 250 records for each table

- src/common/table.rs
> Improve table.rs code

- Justfile
> remove ignore for obsolete advisory warning

- src/common/table.rs
> Add padding to last column in the table

- cypress/e2e/not-found/not-found.cy.js
- src/common/components.rs
- src/transactions/page.rs
> Implement `Txn Not Found` Page

- src/common/components.rs
> Default page container fill 85% of view height

- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/e2e/table/dynamic-table-height.cy.js
- cypress/support/commands.js
- src/account_activity/components.rs
- src/account_activity/page.rs
- src/blocks/components.rs
- src/common/components.rs
- src/common/constants.rs
- src/common/functions.rs
- src/common/models.rs
- src/next_stakes/page.rs
- src/snarks/page.rs
- src/stakes/page.rs
- src/tokens/page.rs
- src/transactions/components.rs
- src/zk_apps/page.rs
> Add dynamic number of table rows depending on page size.

- cypress/e2e/spotlight/block-spotlight.cy.js
- src/blocks/components.rs
- src/blocks/page.rs
> add coinbase to internal commands tab

- cypress/e2e/account-dialog/dialog-contents.cy.js
- cypress/e2e/account/account-table.cy.js
- cypress/e2e/all/account-page.cy.js
- cypress/e2e/elements/pill.cy.js
- cypress/e2e/empty-table/empty-table.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/navigation/to-transactions.cy.js
- cypress/e2e/not-found/not-found.cy.js
- cypress/e2e/pagination/all.cy.js
- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/spotlight/transaction-spotlight.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- cypress/e2e/table/dynamic-table-height.cy.js
- cypress/pages.json
- src/account_activity/components.rs
- src/account_activity/page.rs
- src/account_activity/table_traits.rs
- src/blocks/table_traits.rs
- src/header/navigation.rs
- src/root.rs
- src/transactions/components.rs
- src/transactions/page.rs
- src/transactions/table_trait.rs
- src/zk_apps/page.rs
- src/zk_apps/table_trait.rs
> Refactor "Transactions" to "Commands"

- cypress/e2e/tabs/tabs.cy.js
- src/common/components.rs
- src/user_commands/page.rs
> Correctly link to `internal commands` from tab link

- cypress/e2e/navigation/to-transactions.cy.js
- cypress/e2e/spotlight/transaction-spotlight.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- src/account_activity/table_traits.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
- src/zk_apps/page.rs
> Fix misnomers concerning `txn hash`

- src/summary/page.rs
> `Height` -> `Block Height` on the summary page

- cypress/e2e/empty-table/empty-table.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/pagination/all.cy.js
- cypress/e2e/search-bar/search-bar-integration.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/stakes/staking-page.cy.js
- cypress/e2e/table/dynamic-table-height.cy.js
- cypress/pages.json
- graphql/queries/next_staking_ledgers.graphql
- graphql/queries/staking_ledgers.graphql
- src/header/navigation.rs
- src/next_stakes/functions.rs
- src/next_stakes/graphql.rs
- src/next_stakes/page.rs
- src/next_stakes/table_traits.rs
- src/root.rs
- src/stakes/functions.rs
- src/stakes/graphql.rs
- src/stakes/table_trait.rs
> Fix misnomer for `stakes` and `next-stakes`

- cypress/e2e/empty-table/empty-table.cy.js
- cypress/e2e/search-bar/search-bar-integration.cy.js
- src/blocks/components.rs
- src/blocks/functions.rs
- src/blocks/models.rs
- src/blocks/page.rs
- src/common/constants.rs
- src/common/functions.rs
- src/common/models.rs
- src/summary/page.rs
> Multi Search box on home page and blocks page

- src/common/components.rs
- src/common/search.rs
- src/common/spotlight.rs
- src/footer/mod.rs
- src/header/navigation.rs
- src/stakes/components.rs
- src/summary/components.rs
- src/summary/page.rs
> Alter desktop layout to optimize space

- cypress/e2e/stakes/staking-page.cy.js
> fix flakey test

- Justfile
> 'just publish' first cleans, then builds/publishes, then rebuilds node_modules

- cypress/e2e/pagination/all.cy.js
- src/common/models.rs
- src/common/table.rs
- src/icons/mod.rs
> Add first and last pagination buttons

- cypress/e2e/stakes/staking-page.cy.js
- src/next_stakes/page.rs
- src/stakes/components.rs
- src/stakes/mod.rs
- src/stakes/page.rs
> Keep buttons consistent between next stakes and stakes page

- src/stakes/table_trait.rs
> Make ledger hash copiable on staking page

- cypress/e2e/global-search/search.cy.js
- src/account_activity/page.rs
- src/blocks/page.rs
- src/common/constants.rs
- src/common/search.rs
- src/next_stakes/page.rs
- src/root.rs
- src/snarks/page.rs
- src/stakes/page.rs
- src/summary/page.rs
- src/user_commands/page.rs
> Add global search bar to quickly navigate to parts of site

- cypress/e2e/columnar-search/all.cy.js
- cypress/e2e/empty-table/empty-table.cy.js
- src/next_stakes/functions.rs
- src/next_stakes/page.rs
- src/next_stakes/table_traits.rs
- src/stakes/functions.rs
- src/stakes/page.rs
- src/stakes/table_trait.rs
> Add columnar search for all staking ledgers

- cypress.config.js
- cypress/e2e/account-dialog/dialog-contents.cy.js
- cypress/e2e/all/account-page.cy.js
- cypress/e2e/canonicity/tables.cy.js
- cypress/e2e/navigation/to-blocks.cy.js
- cypress/e2e/navigation/to-snarks.cy.js
- cypress/support/commands.js
> Consolidate cypress configuration code

- assets/manifest.webmanifest
- cypress/e2e/blocks/tabs.cy.js
- src/common/components.rs
- src/header/navigation.rs
> Add sub-menu for txn menu item

- cypress/e2e/stakes/staking-page.cy.js
- src/header/navigation.rs
> Add submenu for staking menu item

- src/common/search.rs
> Clear input in global search if match is found

- cypress/e2e/blocks/tabs.cy.js
- cypress/e2e/global-search/search.cy.js
- cypress/e2e/spotlight/account-spotlight.cy.js
- cypress/e2e/stakes/staking-page.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- src/account_activity/functions.rs
- src/account_activity/table_traits.rs
- src/blocks/functions.rs
- src/blocks/table_traits.rs
- src/common/components.rs
- src/common/search.rs
- src/header/navigation.rs
- src/snarks/functions.rs
- src/snarks/table_trait.rs
- src/zk_apps/page.rs
> remove voting_for and work_ids

- cypress/e2e/columnar-search/all.cy.js
- cypress/e2e/pagination/all.cy.js
- src/account_activity/components.rs
- src/account_activity/page.rs
- src/blocks/components.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/next_stakes/page.rs
- src/snarks/page.rs
- src/stakes/page.rs
- src/tokens/page.rs
- src/user_commands/components.rs
- src/zk_apps/page.rs
> Refactor table component to facilitate independent rendering of table header (`<th>`) and table data (`<td>`)

- src/blocks/components.rs
> Render table header, table data, and pagination independently on summary page

- cypress/e2e/spotlight/block-spotlight.cy.js
- graphql/queries/blocks.graphql
- src/account_activity/table_traits.rs
> Remove vestiges of the snark work ids and Winning Accounts

- cypress/e2e/spotlight/transaction-spotlight.cy.js
- graphql/queries/transactions.graphql
- src/user_commands/models.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
> Remove Payment ID

- src/common/models.rs
- src/common/table.rs
- src/user_commands/components.rs
> Render table header, table data, and pagination independently on user commands page

- cypress/e2e/pagination/all.cy.js
- src/common/models.rs
- src/common/table.rs
- src/internal_commands/components.rs
> Render table header, table data, and pagination independently on Internal Commands page

- graphql/queries/blocks.graphql
- src/blocks/components.rs
- src/blocks/page.rs
- src/user_commands/models.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/603
* Integrate blocks page and homepage with the mina indexer
> Blocks columnar work

- cypress/e2e/pagination/all.cy.js
- src/stakes/page.rs
> Render table header, table data, and pagination independently on Stakes page

- cypress/e2e/pagination/all.cy.js
- src/next_stakes/page.rs
> Render table header, table data, and pagination independently on Next Stakes page

- src/account_activity/components.rs
- src/snarks/components.rs
Resolves Granola-Team/mina-block-explorer#616
> Update verbiage from "Showing latest x..." to "x most recent..."

- src/header/navigation.rs
Fixes Granola-Team/mina-block-explorer#559
> Point "Addresses" menu to `/addresses/accounts`

- cypress/e2e/navigation/mobile-navigation.cy.js
- src/common/components.rs
- src/header/navigation.rs
> Make mobile menu items visible

- README.md
- Trunk.toml
- build.rs
- src/account_activity/page.rs
- src/common/constants.rs
- src/config.rs
- src/header/navigation.rs
- src/main.rs
- src/root.rs
- src/user_commands/page.rs
> Remove need for config.rs file & update docs

- src/next_stakes/functions.rs
- src/next_stakes/table_traits.rs
- src/stakes/functions.rs
- src/stakes/table_trait.rs
Fixes Granola-Team/mina-block-explorer#625
> fix(staking): stake amount use total delegated instead of balance

- cypress/e2e/canonicity/tables.cy.js
- cypress/e2e/columnar-search/all.cy.js
- cypress/e2e/navigation/to-block-spotlight.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- graphql/queries/internal_commands.graphql
- src/internal_commands/components.rs
- src/internal_commands/functions.rs
- src/internal_commands/graphql.rs
- src/internal_commands/table_traits.rs
> Add missing columns to internal commands table

- cypress/e2e/pagination/all.cy.js
- src/account_activity/components.rs
- src/blocks/components.rs
- src/internal_commands/components.rs
- src/next_stakes/page.rs
- src/snarks/page.rs
- src/user_commands/components.rs
> Ensure pagination is always visible when scrolling table horizontally

- src/summary/page.rs
Resolves Granola-Team/mina-block-explorer#636
> Dedupe summary page code block

- cypress/e2e/footer/visibility.cy.js
- cypress/e2e/navigation/to-granola.cy.js
- src/footer/mod.rs
> Make footer content visible on mobile

- Justfile
- Trunk.toml
- cypress/e2e/analytics/render.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- index.html
- src/analytics/mod.rs
- src/analytics/page.rs
- src/common/components.rs
- src/common/models.rs
- src/header/navigation.rs
- src/icons/mod.rs
- src/index.html
- src/main.rs
- src/root.rs
- src/scripts/analytics/internal-commands.js
> Add Fee Transfers Analytics

- Justfile
> Publish from dist folder

- src/account_activity/components.rs
- src/account_activity/functions.rs
- src/account_activity/table_traits.rs
- src/blocks/components.rs
- src/blocks/table_traits.rs
- src/common/functions.rs
- src/internal_commands/table_traits.rs
- src/next_stakes/table_traits.rs
- src/snarks/table_trait.rs
- src/stakes/table_trait.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
- src/zk_apps/page.rs
- src/zk_apps/table_trait.rs
> Show `0` instead of `0 MINA` 

- cypress/e2e/global-search/search.cy.js
> fix bug in CI tests for global search

- cypress/e2e/empty-table/empty-table.cy.js
- src/account_activity/components.rs
- src/account_activity/page.rs
- src/blocks/components.rs
- src/blocks/table_traits.rs
- src/common/components.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/next_stakes/page.rs
- src/snarks/page.rs
- src/tokens/page.rs
- src/tokens/table_trait.rs
- src/user_commands/components.rs
- src/zk_apps/functions.rs
- src/zk_apps/page.rs
- src/zk_apps/table_trait.rs
> Incorporate "No data for this view" fallback when search produces no data

- cypress/e2e/blocks/tabs.cy.js
- src/common/table.rs
> Use table-fixed and adjust sizes of table on smaller screens

- build.rs
- cypress/e2e/columnar-search/all.cy.js
- cypress/e2e/empty-table/empty-table.cy.js
- cypress/e2e/exploration/metadata.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- graphql/queries/accounts.graphql
- graphql/schemas/mina-explorer.graphql
- src/account_activity/functions.rs
- src/account_activity/models.rs
- src/account_activity/page.rs
- src/account_activity/table_traits.rs
- src/accounts/functions.rs
- src/accounts/graphql.rs
- src/accounts/mod.rs
- src/accounts/models.rs
- src/accounts/page.rs
- src/accounts/table_traits.rs
- src/common/constants.rs
- src/main.rs
- src/root.rs
> Connect Accounts Page to the Indexer

- src/common/table.rs
> make table headers sticky on desktop

- src/common/table.rs
> fix table header padding

- Justfile
Relates to Granola-Team/mina-block-explorer#44 and Granola-Team/mina-block-explorer#700
> fix(CD): ensure we deploy to Prod

- ops/buildkite-pipeline.yaml
This reverts commit c8dcdef6b7380d84867f5949070150b556444d0f.
> Revert "skip tests if on main (#713)"

- src/root.rs
- src/scripts/analytics/internal-commands.js
> Use last 500 blocks instead of last 24 hours for fee transfer analytics page

- src/common/search.rs
Closes Granola-Team/mina-indexer#964
> Use stakes endpoint for navigation by ledger hash

- cypress/e2e/global-search/search.cy.js
- src/common/search.rs
> Connect global search bar to indexer

- src/scripts/analytics/internal-commands.js
> Add scatter plot to fee transfer analytics to indicate totals per slot 

- build.rs
- cypress/e2e/columnar-search/single-search-result.cy.js
- cypress/e2e/columnar-search/slow-typing-keeps-focus.cy.js
- cypress/e2e/exploration/metadata.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/stakes/staking-page.cy.js
> Connect to indexer REST url

- src/common/functions.rs
> Use abbreviated words in age column

- src/common/constants.rs
- src/footer/mod.rs
> add link to version for API in footer

- cypress/e2e/table-columns/ordered-columns.cy.js
- graphql/queries/staking_ledgers.graphql
- graphql/schemas/mina-explorer.graphql
- src/stakes/functions.rs
- src/stakes/page.rs
- src/stakes/table_trait.rs
> Add username for stakes page

- cypress/support/commands.js
- src/account_activity/components.rs
- src/accounts/page.rs
- src/blocks/components.rs
- src/common/table.rs
- src/icons/mod.rs
- src/internal_commands/components.rs
- src/snarks/page.rs
- src/stakes/components.rs
- src/stakes/page.rs
- src/tokens/page.rs
- src/user_commands/components.rs
- src/zk_apps/page.rs
> Indicate sort direction (hard coded)

- build.rs
- cypress/e2e/columnar-search/multiple-search-results.cy.js
- cypress/e2e/navigation/to-block-spotlight.cy.js
- src/account_activity/functions.rs
- src/accounts/functions.rs
- src/blocks/functions.rs
- src/common/constants.rs
- src/common/search.rs
- src/footer/mod.rs
- src/internal_commands/functions.rs
- src/root.rs
- src/scripts/analytics/internal-commands.js
- src/stakes/functions.rs
- src/user_commands/functions.rs
> Connect snarks page to indexer

- cypress/e2e/user-commands/memo.cy.js
- src/account_activity/models.rs
- src/common/functions.rs
- src/user_commands/functions.rs
- src/user_commands/table_trait.rs
> Place memo under txn hash in all tables

- src/accounts/page.rs
- src/common/constants.rs
- src/stakes/components.rs
> Widen the username column

- Cargo.lock
- Cargo.toml
- cypress/e2e/exploration/metadata.cy.js
- cypress/e2e/stakes/staking-page.cy.js
- src/blocks/components.rs
- src/common/components.rs
- src/common/constants.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/root.rs
- src/snarks/page.rs
- src/stakes/page.rs
- src/summary/components.rs
- src/summary/mod.rs
- src/summary/models.rs
- src/summary/page.rs
- src/user_commands/components.rs
> Update tables with total record counts

- cypress/e2e/exploration/metadata.cy.js
- src/accounts/page.rs
- src/summary/models.rs
> Integrate total accounts metadata

- src/stakes/functions.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/791
* make percentages consistent with one another
> (stakes) make percentages consistent with one another

- src/common/functions.rs
- src/summary/components.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/792
* Format all numeric values in the summary
> Format all numeric values in the summary

- src/account_activity/graphql.rs
- src/blocks/graphql.rs
- src/snarks/graphql.rs
- src/stakes/graphql.rs
> Use `#[derive(Default)]` where possible with graphql generated modules

- Justfile
This commit reorders the Justfile recipes so that they appear in a topologically sorted order. That is, if the recipes are trees of dependencies, then the leaves must appear first, and any non-leaf recipe must appear before the non-leaf recipes that use it. This helps the developer to test the recipes in an order that is efficient, and helps the user understand which recipes are likely used by which other recipes (earlier ones are used by later ones, only).
This commit also removes the 'build' recipe, which, interestingly, is not used by any other recipes or in production.
The unnecessary 'build' is also removed from the 'lint' recipe (invoked by 'test' in CI), hopefully making it faster.
> Adjust Justfile just so it is just so

- cypress/e2e/spotlight/CkpZhvEYxb9YFZULWEw61khrHAqGZhTktZSiGQ1CKfe6n2TcnxdgD.cy.js
- src/user_commands/components.rs
- src/user_commands/functions.rs
- src/user_commands/graphql.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
Closes Granola-Team/mina-indexer#1092
> Specify block when visiting command spotlight

- src/blocks/functions.rs
Fixes: https://github.com/Granola-Team/mina-block-explorer/issues/827
> (blocks) use slot for slot

- cypress/e2e/stakes/staking-page.cy.js
- cypress/e2e/table-columns/ordered-columns.cy.js
- graphql/queries/blocks.graphql
- src/blocks/components.rs
- src/blocks/functions.rs
- src/blocks/table_traits.rs
> Add txn type into block spotlight user commands table

- flake.lock
- flake.nix
Without this change, the packages chosen will differ on dev machines from one another and from the CI machines and prod machine(s). (That happens because the 'nixpkgs' used is not guaranteed to be the same package set, without this change.)
> Pin nixpkgs and use nixfmt

- pnpm-lock.yaml
1st: `rm pnpm-lock.yaml`
2nd: Run `pnpm install`
Fixes Granola-Team/mina-block-explorer#833
> fix: update pnpm lockfile format

- src/blocks/components.rs
- src/summary/components.rs
Fixes Granola-Team/mina-block-explorer#808
> fix: "Total Currency" -> "Total MINA"

- cypress/e2e/global-search/search.cy.js
- src/common/search.rs
> Navigate to block height if epoch not existent

- cypress/e2e/constants.js
- cypress/e2e/seo-optimization/titles.cy.js
- src/account_activity/page.rs
> Remove ticks in username in <title>

- src/blocks/components.rs
> Use pill for "canonical" in block spotlight

- cypress/e2e/constants.js
- cypress/e2e/tables/tables.cy.js
- graphql/queries/blocks.graphql
- src/blocks/functions.rs
- src/blocks/table_traits.rs
> Add memo to block user commands

- cypress/e2e/constants.js
- cypress/e2e/document/charting-scripts.cy.js
- cypress/e2e/tables/tables.cy.js
- graphql/queries/account_dialog.graphql
- src/account_activity/table_traits.rs
- src/blocks/functions.rs
> Use slot is slot_since_genesis for various blocks tables

- cypress/e2e/summary/overview.cy.js
- src/summary/components.rs
> Update metric label to Blockchain Length

- cypress/e2e/tables/tables.cy.js
- graphql/schemas/mina-explorer.graphql
- src/account_activity/functions.rs
- src/accounts/functions.rs
- src/accounts/page.rs
> Make accounts searchable by balance

- Justfile
> Add test parameter to enable running specific tests

- cypress/e2e/constants.js
- cypress/e2e/helpers.js
- cypress/e2e/localisation/numbers.cy.js
- cypress/e2e/stakes/staking-page.cy.js
- cypress/e2e/summary/overview.cy.js
- cypress/e2e/tables/tables.cy.js
- src/account_activity/functions.rs
- src/account_activity/models.rs
- src/account_activity/table_traits.rs
- src/accounts/table_traits.rs
- src/blocks/functions.rs
- src/common/functions.rs
- src/common/table.rs
- src/internal_commands/table_traits.rs
- src/snarks/functions.rs
- src/stakes/components.rs
- src/summary/components.rs
- src/user_commands/table_trait.rs
- src/zk_apps/table_trait.rs
> Format numbers according to language settings in browser

- cypress/support/commands.js
- src/account_activity/components.rs
- src/accounts/page.rs
- src/blocks/components.rs
- src/common/functions.rs
- src/common/models.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/snarks/page.rs
- src/stakes/components.rs
- src/user_commands/components.rs
- src/zk_apps/page.rs
> Implement new metadata function to display 3 numbers: display, available, total

- cypress/e2e/constants.js
- cypress/e2e/tables/tables.cy.js
- cypress/support/commands.js
- graphql/queries/blocks.graphql
- src/blocks/components.rs
- src/blocks/functions.rs
- src/blocks/table_traits.rs
- src/common/components.rs
- src/common/functions.rs
- src/common/models.rs
> Add "status" column to Block Spotlight -> User Commands table for Applied/Not Applied Txns

- cypress/e2e/localisation/numbers.cy.js
- cypress/e2e/tables/tables.cy.js
- cypress/support/commands.js
- src/blocks/table_traits.rs
- src/user_commands/components.rs
- src/user_commands/table_trait.rs
> Add "status" column to User Commands table

- cypress/e2e/navigation/to-blocks.cy.js
- cypress/e2e/navigation/to-snarks.cy.js
- src/account_activity/components.rs
> Fix broken link to snarks and blocks pages from account spotlight

- cypress/e2e/localisation/numbers.cy.js
- src/common/functions.rs
> Remove trailing zeros on all Mina

- src/account_activity/components.rs
- src/accounts/page.rs
- src/blocks/components.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/snarks/page.rs
- src/user_commands/components.rs
- src/user_commands/page.rs
> Restrict inputs for height filter to numeric values

- src/blocks/components.rs
- src/snarks/page.rs
- src/summary/page.rs
- src/user_commands/components.rs
> Skip API requests when page is not visible

- src/account_activity/models.rs
- src/blocks/functions.rs
- src/common/constants.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
- src/zk_apps/page.rs
> Title case the 'kind' column

- css/styles.css
- src/common/search.rs
- src/header/navigation.rs
- src/icons/mod.rs
Resolves Granola-Team/mina-block-explorer#913
> feat: beta ribbon

- cypress/e2e/footer/visibility.cy.js
- src/footer/mod.rs
> Footer changes

- cypress/e2e/localisation/numbers.cy.js
- cypress/e2e/spotlight/CkpZhvEYxb9YFZULWEw61khrHAqGZhTktZSiGQ1CKfe6n2TcnxdgD.cy.js
- cypress/e2e/tables/tables.cy.js
- cypress/support/commands.js
- src/account_activity/components.rs
- src/accounts/page.rs
- src/blocks/components.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/snarks/page.rs
- src/stakes/components.rs
- src/user_commands/components.rs
- src/user_commands/page.rs
> Adjust integer columns to have right-aligned values

- cypress/e2e/localisation/numbers.cy.js
- src/accounts/table_traits.rs
- src/common/constants.rs
- src/common/functions.rs
- src/internal_commands/table_traits.rs
- src/snarks/functions.rs
- src/snarks/table_trait.rs
- src/stakes/functions.rs
- src/stakes/table_trait.rs
- src/user_commands/components.rs
- src/user_commands/table_trait.rs
> Align floating point numbers in tables by the decimal

- cypress/e2e/columnar-search/slow-typing-keeps-focus.cy.js
- cypress/e2e/tables/tables.cy.js
- graphql/queries/staking_ledgers.graphql
- graphql/schemas/mina-explorer.graphql
- src/accounts/page.rs
- src/common/functions.rs
- src/common/models.rs
- src/stakes/components.rs
- src/stakes/page.rs
- src/summary/models.rs
> Update staking ledgers with 3 metadata points

- cypress/e2e/tables/tables.cy.js
- src/stakes/page.rs
> Fix bug with metadata points for staking table

- cypress/e2e/spotlight/transaction-spotlight.cy.js
- cypress/support/commands.js
- src/blocks/table_traits.rs
- src/common/constants.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
> Add status indicator to txn spotlight page

- cypress/e2e/tables/tables.cy.js
- src/account_activity/dialog.rs
- src/account_activity/functions.rs
- src/account_activity/page.rs
> Implement updated block # on account spotlight page

- cypress/e2e/tables/tables.cy.js
- graphql/queries/blocks.graphql
- src/blocks/components.rs
- src/blocks/functions.rs
- src/blocks/table_traits.rs
> Add `Nonce` column to Block -> User Commands table

- src/internal_commands/table_traits.rs
> Add mina currency tag to `fee` column in internal commands table

- src/common/table.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
> Refactor `In Other Blocks` section to use `TableSectionTemplate` component

- Justfile
> Add comments to Justfile for better command line user experience

- Justfile.dev
> Add just command to build/cache docs in home directory

- cypress/e2e/tables/tables.cy.js
- cypress/e2e/tabs/tabs.cy.js
- graphql/queries/account_dialog.graphql
- src/account_activity/components.rs
- src/account_activity/dialog.rs
- src/account_activity/functions.rs
- src/account_activity/graphql.rs
- src/account_activity/page.rs
- src/account_activity/table_traits.rs
- src/root.rs
> Add internal commands to account spotlight page

- cypress/e2e/delegation/broadcast.cy.js
- cypress/e2e/localisation/numbers.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/navigation/to-blocks.cy.js
- cypress/e2e/tables/tables.cy.js
> Resolve all broken tier2 tests

- .envrc
- Justfile
- build.rs
- src/common/constants.rs
- src/header/navigation.rs
- src/root.rs
- src/user_commands/page.rs
> Remove berkeley compile-time feature flag

- src/blocks/components.rs
- src/blocks/page.rs
> Remove coinbase injection from block spotlight internal commands table

- src/blocks/functions.rs
- src/blocks/models.rs
- src/blocks/table_traits.rs
> Include block state hash in link to command spotlight page

- .cargo/audit.toml
Logged https://github.com/Granola-Team/mina-block-explorer/issues/995
> Ignore advisory `RUSTSEC-2024-0370`

- .gitmodules
- Justfile
- README.md
- package.json
> Run a local indexer in CI for front-end e2e tests

- cypress/e2e/analytics/filters.cy.js
- cypress/e2e/analytics/snark-fees.cy.js
- src/analytics/components.rs
- src/root.rs
- src/scripts/analytics/avg-snark-fee-per-block.js
* Bug fixes
* Closes: #992 and #991
> Fix bugs observed in snarks analytics graphs

- Justfile
* Local dev now starts an indexer.
> Default to local indexer for local dev

- cypress/e2e/analytics/filters.cy.js
- cypress/e2e/empty-table/empty-table.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/tables/tables.cy.js
- src/analytics/components.rs
- src/analytics/functions.rs
- src/analytics/models.rs
- src/analytics/page.rs
- src/analytics/table_traits.rs
- src/common/components.rs
- src/common/models.rs
- src/icons/mod.rs
- src/root.rs
> Create Stakers Leaderboard

- cypress/e2e/analytics/filters.cy.js
- cypress/e2e/empty-table/empty-table.cy.js
- cypress/e2e/navigation/to-account.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/tables/tables.cy.js
- src/analytics/components.rs
- src/analytics/functions.rs
- src/analytics/models.rs
- src/analytics/page.rs
- src/analytics/table_traits.rs
- src/root.rs
> Snarker Leaderboard

- cypress/e2e/tables/tables.cy.js
- graphql/schemas/mina-explorer.graphql
- src/account_activity/functions.rs
- src/accounts/functions.rs
- src/accounts/page.rs
Enable filtering by delegate on accounts listing page
#982
> Enable filtering by delegate on accounts listing page

- graphql/queries/account_dialog.graphql
- graphql/schemas/mina-explorer.graphql
- src/account_activity/components.rs
> Add 'available records' to account spotlight page for each tab

- cypress/e2e/tables/tables.cy.js
- graphql/schemas/mina-explorer.graphql
- src/account_activity/models.rs
- src/common/functions.rs
- src/stakes/components.rs
- src/stakes/functions.rs
- src/stakes/graphql.rs
> Enable searching by stake on the staking page

- src/analytics/components.rs
- src/analytics/page.rs
Solved in two different ways:
* Integrating the epoch filtering into the table "controls" section OR
* Merging app sections on pages with charts
#1021
> Solve spacing issues with "filters" app section in analytics pages 

- src/root.rs
- src/scripts/analytics/charts-common.js
The PR introduces a common set of styles for the charts. It does not integrate them into the existing charts yet.
Contributes to (but does not close): #1047
> Make a chart commons file for chart styles and function calls

- src/root.rs
- src/scripts/analytics/charts-common.js
- src/scripts/analytics/user-commands.js
> Integrate styles into user commands

- src/scripts/analytics/avg-snark-fee-per-block.js
Contributes to, but does not close #1047
> Integrate styles into snarks analytics page

- cypress/e2e/analytics/render.cy.js
- src/analytics/page.rs
- src/scripts/analytics/internal-commands.js
Also splitting internal commands chart into two separate charts.
Contributes to, but does not close #1047
> Integrate styles into internal commands

- src/scripts/analytics/blocks.js
⚠️ depends on https://github.com/Granola-Team/mina-block-explorer/pull/1048
Integrate chart styles into block analytics
contributes to, but does not close #1047
> Integrate chart styles into block analytics

- cypress/e2e/analytics/user-command-stats.cy.js
- src/analytics/page.rs
- src/blocks/components.rs
- src/common/components.rs
- src/common/functions.rs
- src/common/models.rs
- src/scripts/analytics/user-commands.js
> Improve legibility of stats on analytics page

- Justfile
- jest.config.js
- package.json
- pnpm-lock.yaml
- src/scripts/analytics/charts-common.js
- src/scripts_tests/charts-common.spec.js
The little bit of javascript we use for charts is untested. This PR fixes that.
Closes: #1059
> Add jest for testing javascript files + one test

- src/scripts/analytics/user-commands.js
> Add missing grid property to charts

- src/common/components.rs
> Make Simple Analytics Info mobile compatible

- Justfile
- src/scripts/analytics/charts-common.js
- src/scripts/analytics/user-commands.js
- src/scripts_tests/charts-common.spec.js
> Show rank instead of truncated key for rank charts

- cypress/e2e/analytics/user-command-stats.cy.js
- cypress/e2e/tables/tables.cy.js
- src/blocks/table_traits.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
> Update mina-indexer from 609f060b to f96828a5

- cypress/e2e/analytics/render.cy.js
- cypress/e2e/analytics/user-command-stats.cy.js
- cypress/e2e/seo-optimization/titles.cy.js
- cypress/e2e/tables/tables.cy.js
- src/analytics/page.rs
- src/blocks/table_traits.rs
- src/root.rs
- src/user_commands/page.rs
- src/user_commands/table_trait.rs
⚠️ depends on #1041 
Move internal commands charts into tab with user commands
Closes: #1050
> Combine analytics charts for internal and user commands

- Justfile
- Justfile.dev
- flake.nix
- ops/manage-processes-spec.rb
- ops/manage-processes.rb
> Make `manage-processes.rb` handle SIGINT

- Justfile
- Justfile.dev
> Improve legibility and usability of Justfile

- cypress/e2e/spotlight/transaction-spotlight.cy.js
- src/user_commands/page.rs
> Make it clear who the fee payer is on the txn spotlight page

- cypress/e2e/tab-number-bubble/tabs.cy.js
- cypress/support/commands.js
- src/account_activity/page.rs
Display total number of "x" per tab, on account spotlight
Closes: #1056
> Display total number of "x" per tab, on account spotlight page

- src/common/components.rs
> Make `NavEntryIcon` common component

- cypress/e2e/analytics/render.cy.js
- src/analytics/page.rs
- src/scripts/analytics/avg-snark-fee-per-block.js
> Split snark graphs into two separate graphs

- src/account_activity/components.rs
- src/account_activity/models.rs
- src/accounts/mod.rs
- src/accounts/models.rs
- src/accounts/page.rs
- src/analytics/components.rs
- src/analytics/functions.rs
- src/analytics/mod.rs
- src/analytics/models.rs
- src/blocks/components.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/snarks/page.rs
- src/stakes/components.rs
- src/stakes/models.rs
- src/tokens/page.rs
- src/user_commands/components.rs
- src/user_commands/page.rs
- src/zk_apps/page.rs
> Parity refactoring of `TableColumn` to allow for generic sorting

- cypress/e2e/analytics/render.cy.js
- src/analytics/page.rs
- src/scripts/analytics/blocks.js
- src/scripts/analytics/charts-common.js
- src/scripts_tests/charts-common.spec.js
> Add Blockchain Tree visualization

- cypress/e2e/analytics/render.cy.js
- cypress/e2e/analytics/snark-stats.cy.js
- src/analytics/page.rs
- src/common/components.rs
- src/scripts/analytics/avg-snark-fee-per-block.js
Add chart to visualize fee distribution on snark page
Closes: #1085
> Chart to visualize snark fee distribution

- cypress/e2e/tables/tables.cy.js
- cypress/support/commands.js
- src/blocks/components.rs
- src/blocks/functions.rs
- src/blocks/page.rs
- src/common/components.rs
- src/common/table.rs
Add row limit for blocks page
Relates to: #1082
> Add row limit for blocks page

- cypress/e2e/analytics/render.cy.js
- src/analytics/page.rs
- src/scripts/analytics/avg-snark-fee-per-block.js
- src/scripts/analytics/charts-common.js
- src/scripts/analytics/user-commands.js
- src/scripts_tests/charts-common.spec.js
> Add SNARK jobs chart

- cypress/e2e/tables/tables.cy.js
- src/accounts/functions.rs
- src/accounts/page.rs
Add row limit to Accounts table
Contributes to: #1082
> Add row limit to Accounts table

- cypress/e2e/tables/tables.cy.js
- src/internal_commands/components.rs
- src/internal_commands/functions.rs
Add row limit to Internal Commands table
Relates to: #1082
> Add row limit to Internal Commands table

- cypress/e2e/tables/tables.cy.js
- src/stakes/components.rs
- src/stakes/functions.rs
> Add row limit to staking ledger table

- src/analytics/page.rs
- src/common/components.rs
> Fix alignment issues with AnalyticsSimpleInfo component

- src/accounts/page.rs
- src/common/table.rs
- src/icons/mod.rs
- src/stakes/models.rs
Make it possible to integrate state changes with URL `sort-dir` parameter, and table column icons
Relates to: #1091
> Allow for URL and Table Icon integration

- src/account_activity/components.rs
- src/accounts/page.rs
- src/analytics/components.rs
- src/blocks/components.rs
- src/common/table.rs
- src/internal_commands/components.rs
- src/snarks/page.rs
- src/stakes/components.rs
- src/stakes/page.rs
- src/tokens/page.rs
- src/user_commands/components.rs
- src/user_commands/page.rs
- src/zk_apps/page.rs
also: update SNARKs and zkApp wording to be consistent
> feat(staking): make epoch selectable in header

- src/common/models.rs
- src/header/navigation.rs
- src/root.rs
> Remove links to berkeley features
